/control/verbose 0 
/run/verbose 0 
/vis/disable 
/det/field 1 
/det/target/material G4_lH2 
/det/target/Z 1 
/det/target/A 2 
/det/target/width 0.001 
/det/target/pos 0. 0. 301. 
/det/primary/energy 30 MeV 
/det/primary/Z 5 
/det/primary/A 8 
/det/primary/pos 0. 0. -90.00 
/det/recoil/A 3 
/det/recoil/Z 2 
/det/ejectile/A 7 
/det/ejectile/Z 4 
/det/currentValue 31.50 
/det/currentValue2 32.00 
/det/update 
/run/beamOn 100
